---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/recipes/searches":
    post:
      summary: Search a recipe
      tags:
      - Recipes
      parameters:
      - name: q
        in: headers
        schema:
          type: string
      responses:
        '200':
          description: recipes
  "/api/v1/recipes/{id}":
    get:
      summary: Retrieves a recipe
      tags:
      - Recipes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: recipe found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: uuid
                  author:
                    type: string
                  content:
                    type: string
                  ingredients:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: uuid
                        food_id:
                          type: uuid
                        name:
                          type: string
                        quantity:
                          type: integer
                        unit:
                          type: string
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                  license:
                    type: string
                  source_url:
                    type: string
                  title:
                    type: string
                  total_minutes:
                    type: integer
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
  "/api/v1/recipes":
    post:
      summary: Creates a recipe
      tags:
      - Recipes
      parameters: []
      responses:
        '200':
          description: recipe created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                content:
                  type: string
                ingredients_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      quantity:
                        type: integer
                      unit:
                        type: string
                      food_id:
                        type: uuid
                license:
                  type: string
                source_url:
                  type: string
                title:
                  type: string
                total_minutes:
                  type: integer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.encuisine.org
